name: Main
on:
  schedule:
    - cron: "*/10 * * * *"
jobs:
  build:
    name: Call Netlify build hook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/608eb5db3b6a4abb68166930
