backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "docs"
    label: "Docs"
    label_singular: "Docs"
    folder: "static/docs"
    create: true
    fields:
       - {label: "Title", name: "t", widget: "string"}
       - {label: "Body", name: "c", widget: "markdown"}