backend:
  name: git-gateway
  repo: SpaceBuckets/SpaceBuckets
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'builds'
    label: 'Builds'
    folder: 'static/builds'
    path: '{{slug}}/{{slug}}'
    format: 'frontmatter'
    media_folder: ''
    public_folder: ''    
    create: true
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 't', widget: 'string' }
      - { label: 'Publish Date', name: 'd', widget: 'datetime' }
      - { label: 'Body', name: 'c', widget: 'markdown' }
      - { label: 'Tags', name: 'g', widget: 'string' }
      - { label: 'Amazon', name: 'z', widget: 'string' }
      - {label: Image1, name: image, widget: file }                      